/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        surface: '#fbf9f5',
        'surface-container-highest': '#e4e2de',
        'surface-container-high': '#eae8e4',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#baeced',
        'on-surface-variant': '#404848',
        'secondary-fixed-dim': '#e6c183',
        secondary: '#755a26',
        'on-secondary-container': '#785c29',
        'on-primary-container': '#8cbdbf',
        'tertiary-fixed-dim': '#c0c8c8',
        'inverse-surface': '#30312e',
        'on-tertiary-container': '#adb5b5',
        'surface-container': '#efeeea',
        'on-error-container': '#93000a',
        tertiary: '#293131',
        'surface-dim': '#dbdad6',
        'on-primary-fixed': '#002021',
        'tertiary-fixed': '#dce4e4',
        outline: '#707979',
        'surface-tint': '#366668',
        'on-tertiary-fixed-variant': '#404849',
        'on-secondary-fixed': '#271900',
        'on-error': '#ffffff',
        primary: '#003638',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#1c4e50',
        'secondary-fixed': '#ffdea8',
        'outline-variant': '#c0c8c8',
        'inverse-on-surface': '#f2f0ed',
        'primary-container': '#1b4d4f',
        'secondary-container': '#fdd798',
        'inverse-primary': '#9fcfd1',
        'surface-container-low': '#f5f3ef',
        'on-primary': '#ffffff',
        background: '#fbf9f5',
        'on-secondary-fixed-variant': '#5b4311',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#e4e2de',
        'surface-bright': '#fbf9f5',
        'primary-fixed-dim': '#9fcfd1',
        'on-surface': '#1b1c1a',
        'on-background': '#1b1c1a',
        'on-tertiary-fixed': '#151d1d',
        'tertiary-container': '#3f4748',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        margin: '32px',
        gutter: '24px',
        sm: '12px',
        lg: '48px',
        base: '8px',
        md: '24px',
        xl: '80px',
      },
      fontFamily: {
        'display-lg': ['Public Sans', 'sans-serif'],
        'headline-md': ['Public Sans', 'sans-serif'],
        'label-md': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'headline-lg': ['Public Sans', 'sans-serif'],
        'headline-lg-mobile': ['Public Sans', 'sans-serif'],
        caption: ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
